openapi: 3.0.0
info:
  version: "1.0.0"
  title: Iris_Breed_Predictor
  description: A application that predicts Iris Breed
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Iris Breed REST
  license:
    name: Apache
paths:
  /Prediction/{id}:
    get:
      tags:
        - Prediction
      operationId: prediction.predPrint
      description: Returns predicted breed of iris
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
      responses:
        '200':
          description: 'CPU info, or add more text'


servers:
  - url: 'http://localhost:8080'
